services:

  db:
    image: postgis/postgis:16-3.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped
  
  
  web:
    build: .
    command: gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 --workers 4
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - tmp_uploads_volume:/app/tmp_uploads
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "127.0.0.1:8000:8000"

  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/app
      - tmp_uploads_volume:/app/tmp_uploads
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
      - redis
    env_file:
      - .env
    restart: always
  

volumes:
  postgres_data:
  static_volume:
  media_volume:
  tmp_uploads_volume:

