# Generated by Django 6.0.6 on 2026-07-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_is_patpal_user_is_petpal_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_data_consent',
            field=models.BooleanField(default=False),
        ),
    ]
